import { Fragment } from "react";import { notFound } from "next/navigation";import { db,safe } from "@/lib/db";import { setStatus } from "@/lib/admin-actions";import { KINDS } from "@/lib/kinds";import { requireAdmin } from "@/lib/authz";
export default async function Inbox({params,searchParams}:{params:{kind:string};searchParams:{q?:string;s?:string;page?:string}}){
 await requireAdmin();const k=KINDS[params.kind];if(!k)notFound();const q=searchParams.q?.trim();
 const where:any={...(searchParams.s&&k.statuses.includes(searchParams.s)?{status:searchParams.s}:{}),...(q?{OR:k.search.map(f=>({[f]:{contains:q,mode:"insensitive"}}))}:{})};
 const pg=Math.max(1,parseInt(searchParams.page||"1")||1);const total:number=await safe(()=>(db as any)[k.model].count({where}),0);
 const rows:any[]=await safe(()=>(db as any)[k.model].findMany({where,orderBy:{createdAt:"desc"},skip:(pg-1)*25,take:25}),[]);
 const qs=(n:number)=>"?"+new URLSearchParams({...(q?{q}:{}),...(searchParams.s?{s:searchParams.s}:{}),page:String(n)});
 return <><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="!text-3xl">{k.title}</h1><a href={"/api/export/"+params.kind} className="btn btn-o">Export CSV</a></div>
 <form className="my-5 flex flex-wrap gap-2"><input name="q" defaultValue={q} placeholder="Search" aria-label="Search" className="input !w-60"/><select name="s" defaultValue={searchParams.s||""} className="input !w-40" aria-label="Status"><option value="">All statuses</option>{k.statuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn">Filter</button></form>
 {rows.length===0?<p className="muted">Nothing here yet.</p>:<ul className="grid gap-3">{rows.map(r=><li key={r.id} className="card !p-4"><dl className="grid gap-1 text-sm sm:grid-cols-[130px_1fr]">{Object.entries(r).filter(([n,v])=>!["id","updatedAt","status"].includes(n)&&v).map(([n,v])=><Fragment key={n}><dt className="font-semibold">{n}</dt><dd className="break-words">{String(v)}</dd></Fragment>)}</dl>
 <form action={setStatus} className="mt-3 flex gap-2"><input type="hidden" name="kind" value={params.kind}/><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue={r.status} className="input !w-44" aria-label="Status">{k.statuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn !py-2">Update</button></form></li>)}</ul>}<nav aria-label="Pagination" className="mt-6 flex flex-wrap items-center gap-4">{pg>1&&<a className="underline" href={qs(pg-1)}>← Newer</a>}{pg*25<total&&<a className="underline" href={qs(pg+1)}>Older →</a>}<span className="muted text-sm">{total} total</span></nav></>}
