import { db,safe } from "@/lib/db";import { requireAdmin } from "@/lib/authz";import { createUser,setRole,setActive,resetPassword,deleteUser } from "@/lib/admin-actions";import ConfirmButton from "@/components/ConfirmButton";
const E:Record<string,string>={invalid:"Invalid details. Passwords need 12+ characters with upper-case, lower-case and a number.",exists:"A user with that email already exists.",last:"You cannot demote, disable or delete yourself or the last active administrator."};
export default async function Users({searchParams}:{searchParams:{error?:string;ok?:string}}){const me=await requireAdmin();
 const u=await safe(()=>db.adminUser.findMany({orderBy:{createdAt:"asc"},select:{id:true,email:true,name:true,role:true,active:true}}),[]);
 return <><h1 className="!text-3xl">Admin users</h1>{searchParams.error&&<p role="alert" className="mt-3 rounded-xl bg-red-100 p-3 text-red-900">{E[searchParams.error]}</p>}{searchParams.ok&&<p role="status" className="mt-3 rounded-xl bg-brand/10 p-3">Done.</p>}
 <ul className="mt-6 grid gap-3">{u.map(x=><li key={x.id} className="card !p-4"><p><b>{x.name}</b> · {x.email} · {x.active?"Active":"Disabled"}{x.id===me.id&&" (you)"}</p>
 <div className="mt-3 flex flex-wrap items-center gap-3">
 <form action={setRole} className="flex gap-2"><input type="hidden" name="id" value={x.id}/><select name="role" defaultValue={x.role} aria-label="Role" className="input !w-32 !py-2"><option>ADMIN</option><option>EDITOR</option></select><button className="btn btn-o !px-4 !py-2">Set role</button></form>
 <form action={setActive}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="active" value={String(!x.active)}/><button className="btn btn-o !px-4 !py-2">{x.active?"Disable":"Enable"}</button></form>
 <form action={resetPassword} className="flex gap-2"><input type="hidden" name="id" value={x.id}/><input name="password" type="password" minLength={12} required placeholder="New password" aria-label="New password" autoComplete="new-password" className="input !w-44 !py-2"/><button className="btn btn-o !px-4 !py-2">Reset</button></form>
 <form action={deleteUser}><input type="hidden" name="id" value={x.id}/><ConfirmButton label="Remove" message="Remove this user permanently?"/></form></div></li>)}</ul>
 <h2 className="mt-10 !text-xl">Add user</h2><form action={createUser} className="card mt-3 grid max-w-md gap-3"><label className="lbl">Name<input name="name" required className="input"/></label><label className="lbl">Email<input name="email" type="email" required className="input"/></label><label className="lbl">Role<select name="role" className="input"><option>EDITOR</option><option>ADMIN</option></select></label><label className="lbl">Password (12+ chars, upper, lower, number)<input name="password" type="password" minLength={12} required autoComplete="new-password" className="input"/></label><button className="btn">Create user</button></form></>}
